service:
  name: helloDynamoDB

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
