service:
  name: helloDynamoDB

plugins:
  - serverless-webpack
  - serverless-offline # 用于离线调试

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  createTable:
    # table.ts 文件放到 src 里了，所以要加 src
    handler: src/table.create
    events:
      - http:
          method: get
          path: create
