service:
  name: helloS3

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline # 用于离线调试

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  resize:
    handler: src/resizer/index.handler
    events:
      - http:
          method: get
          # size 和 image 可以在 event.pathParameters 里取到
          path: /{size}/{image}
    environment:
      BUCKET: dynamic-image-resizing
      region: ap-northeast-2
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: "arn:aws:s3:::dynamic-image-resizing/*"
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: "arn:aws:s3:::dynamic-image-resizing/*"

package:
  exclude:
    - layer/**
    - node_modules/**
    - '!node_modules/babel-runtime/**'
    - '!node_modules/sharp/**'
